### ISSUE TITLE
Not working display more than 5 results

### ISSUE THREAD

**Issue by marcofer2010** [komoot/typeahead-address-photon#1]

**Comment by hosuaby** [comment]
Hello, sorry for such a late response. It's working perfect with more that 5 results. Just need not forget to specify limit twice: while configuring engine (limit for photon API) and while configuring typeahead component itself:

```javascript
  var engine = new PhotonAddressEngine({
    lang: 'fr',
    lat: 48.847547,
    lon: 2.351074,
    limit: 10,  // limit for proton API
    onPredictions: showPredictions
  });

  // ...
   
  $('#inpAddress').typeahead({
    hint: true,
    highlight: true,
    minLength: 3
  }, {
    source: engine.ttAdapter(),
    displayKey: 'description',
    limit: 10 // limit for typeahead
  });
```

![Screenshot_komoot](https://user-images.githubusercontent.com/5645920/81419899-54d65d00-914f-11ea-9404-5e37258e591e.png)
