### ISSUE TITLE
Security Alerts

### ISSUE THREAD

**Issue by christophlingg** [komoot/typeahead-address-photon#3]
I got alerted by github about those to version that have security issues:

> komoot/typeahead-address-photon
https://github.com/komoot/typeahead-address-photon
Known high severity security vulnerability in ecstatic v&lt;= 4.1.2, defined in https://github.com/komoot/typeahead-address-photon/blob/master/package-lock.json

> komoot/typeahead-address-photon
https://github.com/komoot/typeahead-address-photon
Known high severity security vulnerability in serialize-javascript v&lt; 3.1.0, defined in https://github.com/komoot/typeahead-address-photon/blob/master/package-lock.json

I am confident enough in node to fix them, could you have a look on it @hosuaby ?

**Comment by hosuaby** [comment]
Yes. Thanks. I am currently working on that library and I will fix security issues in progress

**Comment by hosuaby** [comment]
Fixed
